### ISSUE TITLE
Error: Failed to call git rev-parse --git-dir: exit status 128

### ISSUE THREAD

**Issue by UserName-wang** [NVIDIA-ISAAC-ROS/isaac_ros_map_localization#19] opened 2023-10-05 02:49 UTC
I got an error: **Error: Failed to call git rev-parse --git-dir: exit status 128.**
I just followed the instructions step by step, and I have the error after this command:
cd ~/workspaces/isaac_ros-dev/src/isaac_ros_common && \
  ./scripts/run_dev.sh

environment: L4T:35.4.1, Jetpack:5.1.2

**Comment by jaiveersinghNV** [comment] 2023-10-23 22:44
Could you please confirm which release of Isaac ROS Common you're running this on? If you're not already using the [latest release](https://nvidia-isaac-ros.github.io/releases/index#isaac-ros-2-0-0-october-18-2023), could you please try again using this version?

**Comment by UserName-wang** [comment] 2023-10-23 23:53
Dear @jaiveersinghNV ,
Thank you for your reply!
yes, I always use the latest version. because I had tried several times already (all failed with different errors). 
the command:**git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common.git** should clone the latest version by default.

and I have different error at each time i tried. now i got new error below:
admin@ubuntu:/workspaces/isaac_ros-dev$ cd /workspaces/isaac_ros-dev &&   colcon build --symlink-install &&   source install/setup.bash
Starting >>> isaac_ros_common
Starting >>> isaac_ros_test
Starting >>> nvblox_msgs                                                            
Starting >>> nvblox_ros_common                                                                           
Starting >>> nvblox
Starting >>> nvblox_cpu_gpu_tools                                                                                                                   
Starting >>> nvblox_performance_measurement_msgs                                                                                                        
Starting >>> network_performance_measurement                                                                                                            
Starting >>> nvblox_examples_bringup                                                                                                                    
Starting >>> nvblox_isaac_sim
Starting >>> odometry_flattener                                                                                                                          
--- stderr: nvblox                                                                                                                                         
CMake Warning at /usr/share/cmake-3.22/Modules/FindDoxygen.cmake:460 (message):
  Unable to determine doxygen version: No such file or directory
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindDoxygen.cmake:623 (_Doxygen_find_doxygen)
  /workspaces/isaac_ros-dev/build/nvblox/_deps/ext_stdgpu-src/doc/CMakeLists.txt:7 (find_package)


CMake Error at /usr/share/cmake-3.22/Modules/FindDoxygen.cmake:702 (message):
  Unable to generate Doxyfile template: No such file or directory
Call Stack (most recent call first):
  /workspaces/isaac_ros-dev/build/nvblox/_deps/ext_stdgpu-src/doc/CMakeLists.txt:7 (find_package)


make: *** [Makefile:2433: cmake_check_build_system] Error 1
---
Failed   <<< nvblox [2.70s, exited with code 2]
Aborted  <<< isaac_ros_test [2.94s]
Aborted  <<< nvblox_cpu_gpu_tools [2.65s]
Aborted  <<< nvblox_isaac_sim [2.32s]
Aborted  <<< nvblox_examples_bringup [2.39s]
Aborted  <<< isaac_ros_common [3.01s]
Aborted  <<< nvblox_ros_common [2.79s]
Aborted  <<< nvblox_msgs [2.86s]
Aborted  <<< network_performance_measurement [2.50s]
Aborted  <<< nvblox_performance_measurement_msgs [2.60s]                                                                               
Aborted  <<< odometry_flattener [8.29s]                                   

Summary: 0 packages finished [13.0s]
  1 package failed: nvblox
  10 packages aborted: isaac_ros_common isaac_ros_test network_performance_measurement nvblox_cpu_gpu_tools nvblox_examples_bringup nvblox_isaac_sim nvblox_msgs nvblox_performance_measurement_msgs nvblox_ros_common odometry_flattener
  1 package had stderr output: nvblox
  41 packages not processed
admin@ubuntu:/workspaces/isaac_ros-dev$

**Comment by UserName-wang** [comment] 2023-10-24 01:16
Does this command need some time to complete: cd ~/workspaces/isaac_ros-dev/src/isaac_ros_map_localization && \
  git lfs pull -X "" -I "**/rosbags/". ?

I doubt this command didn’t work properly on my Jetson. because the command line returns immediately without any latency.

**Comment by jaiveersinghNV** [comment] 2023-11-21 00:02
Marking this issue as a duplicate of https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam/issues/125

**Closed by jaiveersinghNV** 2023-11-21 00:02 UTC
Labels: duplicate
